name: Build Root Filesystem

on: [push, pull_request]

jobs:   
  rootfs:
    runs-on: ubuntu-20.04
    container:
      image: miyoocfw/toolchain:master
    env:
      FORCE_UNSAFE_CONFIGURE: 1
    steps:
    - uses: actions/checkout@v2
    - run: pwd
    - run: echo $PATH
    - name: build
      run: make
    - uses: actions/upload-artifact@v2
      with:
        name: rootfs.tar
        path: output/images/rootfs.tar
        if-no-files-found: error # 'error', 'warn', 'ignore'; defaults to `warn`
